### ISSUE TITLE
建议：插件默认是1000秒检查一次推送，建议改为更低 

### ISSUE THREAD

**Issue by luosheng520qaq** [BraveCowardp/nonebot-plugin-biliforward#3]
如题：可能是开发者错把秒当成毫秒？ 默认的配置里面是1000秒才推送一次，个人感觉可以留给用户选择配置或者改为更低

**Comment by BraveCowardp** [comment]
推送的函数最后会启动一个同id定时任务覆盖，如果函数内没有抛出异常的话，装饰器里的时间间隔实际上是不会生效的，目前使用没有遇到什么问题，都是实时推送的
